name: ci
on:
  push:
    branches:
      - "**"

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "zulu"
          java-version: "21.0.5"
          java-package: "jdk"

      - uses: capralifecycle/actions-lib/check-runtime-dependencies@720c52304c0cbc65a26c18f55a8f182cc0d33d84 # v1.7.1

      - name: cache mvn
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: release preparation
        id: prep
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          major_version="$(sed -n "s/^.*<major-version>\([0-9]\{1,\}\)<\/major-version>.*$/\1/p" pom.xml)"
          echo "$major_version" | grep -q "^[0-9]\{1,\}$" || {
            echo "ERROR: Failed to extract <major-version> from pom.xml"
            exit 1
          }
          echo "major-version=$major_version" >> "$GITHUB_OUTPUT"

      - uses: capralifecycle/actions-lib/generate-tag@720c52304c0cbc65a26c18f55a8f182cc0d33d84 # v1.7.1
        id: tag
        with:
          tag-prefix: "${{ steps.prep.outputs.major-version }}"
          tag-type: "punctuated-timestamp-tag"

      - name: resolve dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: "${{ steps.tag.outputs.tag }}"
        # Needs to run compile first in order to resolve sibling dependencies, see https://stackoverflow.com/a/1905927
        run: mvn -B -Drevision="$TAG" -Dtag="$TAG" compile dependency:resolve

      - name: conditional release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONDITIONAL_RELEASE: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          TAG: "${{ steps.tag.outputs.tag }}"

        run: |
          if [ "$CONDITIONAL_RELEASE" = "true" ]; then
            echo "Releasing library with tag '$TAG'"
            mvn -B source:jar deploy scm:tag -Drevision="$TAG" -Dtag="$TAG" \
              org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce -Drules=requireReleaseDeps
          else
            mvn -B -U clean verify
          fi
